### ISSUE TITLE
PETSc MR 6964 causes Channel fluids examples to fail

### ISSUE THREAD

**Issue by jrwrigh** [CEED/libCEED#1470]
*This is an already known failure (and the GitLab CI PETSc build has reverted that commit to allow tests to pass), but I've realized it never made it's way to a full issue and/or discussion on what the issue is or how to possibly address it.*

Starting with [PETSc MR 6964](https://gitlab.com/petsc/petsc/-/merge_requests/6964/), the Channel tests of the fluids example fail. 

My guess is that this has something to do with DMPlex's isoperiodicity, as that is the odd-feature-out between all the fluids tests and the Channel tests.

## What's (probably) happening
- the MR changed `PetscSectionFieldGetTensorDegree_Private` to get the degree of a tensor via it's `PetscDualSpace`.
- The only place `PetscSectionFieldGetTensorDegree_Private` is used is in `DMPlexSetClosurePermutationTensor`, which changes the ordering of the PetscSection DoF ordering to a tensor-product ordering

So as I see it, there are two possible ways the code is changing behavior:
- `PetscSectionFieldGetTensorDegree_Private` incorrectly reports the field as discontinuous
  - This is taken from `PetscDualSpaceLagrangeGetContinuity`
  - That function in turn gets it from a struct member, which is set in `PetscDualSpaceSetUp_Lagrange`
  - That function sets continuity based on the reported order of the dual space and whether it's `formDegree` matches the physical dimension. 
- `PetscSectionFieldGetTensorDegree_Private` does not calculate the tensor degree correctly
  - This is based on `PetscDualSpaceGetDimension`, which is in turn based on the size of the section associated with the PetscDualSpace
  
Unfortunately, I don't see an obvious place where isoperiodicity changes the DualSpace side of things. @jedbrown Any insight/ideas as to where to look?

Paging @rezgarshakeri since you made the PETSc MR.

Edit: The issue is not isoperiodicity per-say, but that periodicity requires using the Cell Coordinate DM, which then registers as discontinuous.

**Comment by knepley** [comment]
I fixed that stuff in https://gitlab.com/petsc/petsc/-/commit/5f82726afd598c9bfa8a3224245f704499d2c233

**Comment by jrwrigh** [comment]
I'm still seeing the issues on `main`, with that commit. These are with hex elements as well.

In https://github.com/CEED/libCEED/blob/72e72e0ec0f1356c4a8e31ae3520f998ca726cd1/examples/fluids/src/dm_utils.c#L490
we get that the dual space is `continuous == PETSC_FALSE`. Manually changing this to `PETSC_TRUE` everytime in gdb now makes the test successful.

Now, the fun part is I'm pretty sure the cell coordinate DualSpace _must_ be discontinuous (since that's kind of the point of the cell DM); feel free to correct me if I'm wrong on that part. 

Assuming that the CellDM should have a discontinuous DualSpace, I'm not sure if there needs to be an exception for cell coordinates in `DMPlexSetClosurePermutationTensor`/`PetscSectionFieldGetTensorDegree_Private`, or if there should be a change in the fluids example.

**Comment by jrwrigh** [comment]
Currently the code prefers getting the local coordinate array from the cell DM if it exists. So I think there needs to be some way of changing the ordering of the CellCoordinateDM's section to a tensor-product ordering.

**Comment by jrwrigh** [comment]
I noticed this comment in the PETSc MR:
> I added a continuity argument to `PetscSectionFieldGetTensorDegree_Private` so we change the permutation for continuous field only but I don't know how we can assign the perm array to the original permutation when the field is discontinuous.

What's the reason that discontinuous fields should keep their original permutation?

**Comment by rezgarshakeri** [comment]
> I noticed this comment in the PETSc MR:
> 
> > I added a continuity argument to `PetscSectionFieldGetTensorDegree_Private` so we change the permutation for continuous field only but I don't know how we can assign the perm array to the original permutation when the field is discontinuous.
> 
> What's the reason that discontinuous fields should keep their original permutation?

The permutation for discontinuous field is in a correct tensor ordering and we confirm that by mixed-elasticity in ratel.

**Comment by rezgarshakeri** [comment]
> I'm still seeing the issues on `main`, with that commit. These are with hex elements as well.
> 
> In
> 
> https://github.com/CEED/libCEED/blob/72e72e0ec0f1356c4a8e31ae3520f998ca726cd1/examples/fluids/src/dm_utils.c#L490
> 
> we get that the dual space is `continuous == PETSC_FALSE`. Manually changing this to `PETSC_TRUE` everytime in gdb now makes the test successful.
> 
> Now, the fun part is I'm pretty sure the cell coordinate DualSpace _must_ be discontinuous (since that's kind of the point of the cell DM); feel free to correct me if I'm wrong on that part.
> 
> Assuming that the CellDM should have a discontinuous DualSpace, I'm not sure if there needs to be an exception for cell coordinates in `DMPlexSetClosurePermutationTensor`/`PetscSectionFieldGetTensorDegree_Private`, or if there should be a change in the fluids example.

When I created that MR and MR after that by Matt, we didn't see any failure in periodic test cases in `ex8.c` petsc. We have these periodic tests
```
  test:
    suffix: 1d_q1_periodic
    requires: !complex
    args: -dm_plex_dim 1 -petscspace_degree 1 -dm_plex_simplex 0 -dm_plex_box_faces 3 -dm_plex_box_bd periodic -dm_view -view_coord
  test:
    suffix: 2d_q1_periodic
    requires: !complex
    args: -dm_plex_dim 2 -petscspace_degree 1 -dm_plex_simplex 0 -dm_plex_box_faces 3,2 -dm_plex_box_bd periodic,none -dm_view -view_coord
  test:
    suffix: 3d_q1_periodic
    requires: !complex
    args: -dm_plex_dim 3 -petscspace_degree 1 -dm_plex_simplex 0 -dm_plex_box_faces 3,2,1 -dm_plex_box_bd periodic,none,none -dm_view -view_coord
  test:
    suffix: 3d_q1_periodic_project
    requires: !complex
    args: -dm_plex_dim 3 -petscspace_degree 1 -dm_plex_simplex 0 -dm_plex_box_faces 1,1,3 -dm_plex_box_bd none,none,periodic -dm_view -view_coord -project_coordinates

  test:
    suffix: 3d_q2_periodic # not actually periodic because only 2 cells
    args: -dm_plex_dim 3 -petscspace_degree 2 -dm_plex_simplex 0 -dm_plex_box_faces 2,2,2 -dm_plex_box_bd periodic,none,periodic -dm_view
```
I think it would be better to reproduce this failure by a test case in `petsc/src/dm/impls/plex/tutorials/ex8.c`

**Comment by jrwrigh** [comment]
You'd only see the failure in those examples if they permuted the tensor for the CellCoordinateDM and then used the coordinate local vector from the CellCoordinateDM for something. Are you use both of those were done?

**Comment by knepley** [comment]
This sounds like an interface mismatch between PETSc and CEED. Let me explain how coordinates work, since I think this is the issue.

The way I handle periodicity, there are two different coordinate charts, a continuous CG (coordinates) and a discontinuous (cell coordinates). The DG coordinates need not cover the whole domain, but it is possible to only have them on cells crossing a branch cut. Jed does something different for isoperodic, so you only get the continuous coordinate chart.

Second, the cell coordinate chart already has the tensor ordering, so the permutation would just be the identity, so that is not the problem.

**Comment by jrwrigh** [comment]
Yeah, sounds like a mismatch. And thanks for the explanation.

> Jed does something different for isoperodic, so you only get the continuous coordinate chart.

Assuming that "continuous" chart refers to the normal CoordinateDM and "discontinuous" chart refers to the CellCoordinateDM, I'm not sure the latter is true? With isoperiodicity, we do have a CellCoordinateDM and need to get coordinates from it rather than the CoordinateDM. ie. `DMGetCellCoordinateDM` returns non-NULL if we have isoperiodicity set and we use that DM for setting up the element restrictions.

> Second, the cell coordinate chart already has the tensor ordering, so the permutation would just be the identity, so that is not the problem.

I'm not sure I follow here. Or at least there's a contradiction in my understanding.

- Previous to the MR, we were doing a permutation (identity or not) to get the tensor ordering in agreement with libCEED's expectations. That was validated as working. 
- After the MR, `DMPlexSetClosurePermutationTensor` detects that the field is discontinuous, performs an identity permutation, but the resulting ordering disagrees with libCEED's expectations.
- From Rezgar's/Ratel's experience and testing, the DMPlex's ordering of discontinuous fields agrees with libCEED's expectation and does not need any modifications

I'm not sure how all three of these statements could be correct at the same time.

**Comment by knepley** [comment]
@jedbrown I thought your isoperiodicity enforced periodic conditions with the L2G map, so that you only used a continuous coordinate space?

Prior to this MR, if you were permuting the DG cell coordinate field, then it was always wrong, even if it matches old output. That field was in tensor order and never needed to be permuted. Either you were looking at continuous coordinates and calling them discontinuous, or the coordinates were not correct.

**Comment by jrwrigh** [comment]
We call `DMLocalizeCoordinates` before calling `DMPlexSetClosurePermutationTensor`, and set `-dm_sparse_localize 0` which looks like it messes with the CellCoordinateDM. Could that be where the ordering for the CellCoordinateDM is getting changed to something other than the tensor ordering?

Also, just to confirm, the permuting CellCoordinateDM ordering does result in correct coordinate locations. The initial conditions are set via coordinate locations. The Channel problem initial condition is only dependent on the y coordinate.
The left image below is uses the PETSc `main`, the right hardcodes `continuous = PETSC_TRUE`.
![image](https://github.com/CEED/libCEED/assets/20801821/179ea321-bcb2-4d51-adc5-460329df2d65)
The left clearly as variation in the z direction where it shouldn't.

So for one reason or another, we need the DG coordinate order permuted.

**Comment by jedbrown** [comment]
Isoperiodic should not use cell coordinates at all. It should behave as a standard continuous space in which the local space ensures that the donor and periodic nodes are distinct with the affine offset applied.

**Comment by jrwrigh** [comment]
Ok, forcing fluids to only ever use the CoordinateDM now has the tests passing.

Currently, the logic was more-or-less to use the CellCoordinateDM over the CoordinateDM if it was available. But isoperiodicity (by some mechanism) does cause the CellCoordinateDM to exist.

**What should the new logic be?**

Should we always ignore the CellCoordinateDM?

**Comment by jedbrown** [comment]
Can we prevent cell coordinates from being created?

**Comment by knepley** [comment]
`dm_sparse_localize` means make DG coordinates for every cell, rather than just those crossing a branch cut.

You should prevent the creation as Jed says. You do not need them, and they must be used in other cases.

We could try and make an example to see what reordering is doing for your problem.

**Comment by jrwrigh** [comment]
The CellCoordinateDM exists right after `DMSetFromOptions`. So I'm not sure where exactly it's getting created.

**Comment by jedbrown** [comment]
What if you delete the `dm_sparse_localize`?

I hate using options for correctness of code anyway, but we shouldn't need it.

**Comment by jrwrigh** [comment]
I currently have gdb running with a watch point on `dm->coordinates[1].dm` to see where that gets written to. 

I can try without the `-dm_sparse_localize` argument, but looking at git history gets me to this commit: https://github.com/CEED/libCEED/commit/3796c4882ea508e8c50f59304fb2ef31152c921a with a helpfully detailed commit message:
```
 examples/fluids: use DMGetCellCoordinateDM to handle periodicity

Note that without -dm_sparse_localize 0 (default=1), the cell DM will
only have cells with localized coordinates (and there is no vector
representation that contains both).
```

Not sure if this was done before or after isoperiodicity was added in.

**Comment by jrwrigh** [comment]
Removing `-dm_sparse_localize` doesn't prevent the creation of the CellCoordinateDM.

**Comment by jedbrown** [comment]
Right, that describes what happens for Matt-style periodicity. This is quite dated now, but it was working when I created it, and I'd hope can work if rebased. https://github.com/CEED/libCEED/pull/1128

**Comment by jrwrigh** [comment]
The CellCoordinateDM is created in a call to `DMLocalizeCoordinates`:
```
#0  DMSetCellCoordinateDM (dm=0x73d790, cdm=0xcfeaf0) at /home/jrwrigh/software/petsc/src/dm/interface/dmcoordinates.c:169
#1  0x00007ffff61dc9a8 in DMLocalizeCoordinates (dm=0x73d790) at /home/jrwrigh/software/petsc/src/dm/interface/dmperiodicity.c:403
#2  0x00007ffff5756037 in DMSetFromOptions_Plex (dm=0x73d790, PetscOptionsObject=0x7fffffffcf10) at /home/jrwrigh/software/petsc/src/dm/impls/plex/plexcreate.c:4406
#3  0x00007ffff60d78ae in DMSetFromOptions (dm=0x73d790) at /home/jrwrigh/software/petsc/src/dm/interface/dm.c:899
#4  0x00000000004828ef in CreateDM (comm=comm@entry=0x7ffff30f9a40 <ompi_mpi_comm_world>, problem=<optimized out>, mat_type=0x4aa023 "aij", vec_type=vec_type@entry=0x4aa004 "standard", dm=dm@entry=0x7fffffffd108)
    at /home/jrwrigh/software/libCEED/examples/fluids/src/setupdm.c:42
#5  0x000000000040af1a in main (argc=<optimized out>, argv=<optimized out>) at /home/jrwrigh/software/libCEED/examples/fluids/navierstokes.c:155
```

Looking at `DMSetFromOptions_Plex`, it doesn't look like there's a way to get around that.

**Comment by jrwrigh** [comment]
Given it's going to be automatically created regardless of what happens, and with `-dm_sparse_localize` turned on its size should be very should minimal, should I just remove all connections to the CellCoordinateDM?

Note doing that would require diverging from some of Ratel's Petsc DM utilities that we've been trying to keep in sync, as it defaults to the cell DM if it's present.

**Comment by jedbrown** [comment]
I think in both cases we can use isoperiodic, and perhaps assert that it is not topological-periodic.

@knepley This is in `DMLocalizeCoordinates`. Can we use `plex->periodic.face_sf` or something so we can skip this for isoperiodic?
```c
  PetscCall(DMGetPeriodicity(dm, NULL, &Lstart, &L));
  /* Cannot automatically localize without L and maxCell right now */
  if (!L) PetscFunctionReturn(PETSC_SUCCESS);
```

@jrwrigh You might be able to trace where `DMSetPeriodicity` is called and prevent it when using `dm_plex_shape zbox` (or other ways that an isoperiodic mesh is created).

**Comment by knepley** [comment]
@jedbrown Sure, we should jsut turn it off there. Here is my diff
```
arcowie/feature-sw-ceed *$:/PETSc3/petsc/petsc-dev$ git diff
diff --git a/include/petsc/private/dmpleximpl.h b/include/petsc/private/dmpleximpl.h
index 879dd61caf8..e4e2f3c0325 100644
--- a/include/petsc/private/dmpleximpl.h
+++ b/include/petsc/private/dmpleximpl.h
@@ -214,7 +214,7 @@ typedef struct {
   PetscErrorCode (*useradjacency)(DM, PetscInt, PetscInt *, PetscInt[], void *); /* User callback for adjacency */
   void *useradjacencyctx;                                                        /* User context for callback */

-  // Periodicity
+  // Isoperiodicity

   struct {
     // Specified by the user
     PetscScalar transform[4][4]; // geometric transform
diff --git a/src/dm/interface/dmperiodicity.c b/src/dm/interface/dmperiodicity.c
index e1a7ac000b7..22d5261ceae 100644
--- a/src/dm/interface/dmperiodicity.c
+++ b/src/dm/interface/dmperiodicity.c
@@ -282,6 +282,7 @@ PetscErrorCode DMGetCoordinatesLocalized(DM dm, PetscBool *areLocalized)
 PetscErrorCode DMLocalizeCoordinates(DM dm)
 {
   DM               cdm, cdgdm, cplex, plex;
+  PetscSF          faceSF;
   PetscSection     cs, csDG;
   Vec              coordinates, cVec;
   PetscScalar     *coordsDG, *anchor, *localized;
@@ -297,6 +298,9 @@ PetscErrorCode DMLocalizeCoordinates(DM dm)
   PetscCall(DMGetPeriodicity(dm, NULL, &Lstart, &L));
   /* Cannot automatically localize without L and maxCell right now */
   if (!L) PetscFunctionReturn(PETSC_SUCCESS);
+  // Isoperiodicity works differently, and we do not need DG coordinates
+  PetscCall(DMPlexGetIsoperiodicFaceSF(dm, &faceSF));
+  if (faceSF) PetscFunctionReturn(PETSC_SUCCESS);
   PetscCall(PetscObjectGetComm((PetscObject)dm, &comm));
   PetscCall(DMGetCoordinatesLocalized(dm, &isLocalized));
   if (isLocalized) PetscFunctionReturn(PETSC_SUCCESS);
   ```
   Do you want me to make a branch, or wait for you folks to test it out?

**Comment by jrwrigh** [comment]
I can test it out in a bit.

**Comment by jrwrigh** [comment]
Hmm, for this specific problem, the face SF isn't set yet. So the CellCoordinateDM is still being created.

**Comment by jrwrigh** [comment]
Well, I've been misspeaking this whole time; the channel examples don't use isoperiodicity (`-dm_plex_shape zbox`), but topological periodicity (`-dm_plex_shape box`, which is default). For some reason I thought we were only ever able to get periodicity working with isoperiodicity rather than topological periodicity.

#### Observations:
1. Turning on `-dm_plex_shape zbox` triggers the 
```c
  PetscCall(DMGetPeriodicity(dm, NULL, &Lstart, &L));
  /* Cannot automatically localize without L and maxCell right now */
  if (!L) PetscFunctionReturn(PETSC_SUCCESS);
```
early exit for `DMLocalizeCoordinates`. So the faceSF isn't even checked. I'm not sure if that will always be true for isoperiodic meshes though; IIRC, we set the spanwise distance in the CGNS reader implementation right now, (though I think that's to force the creation of the CellCoordinateDM that we've been relying on via `DMLocalizeCoordinates`).

2. Turning on `-dm_plex_shape zbox` fails the channel test with a very high error. I'm guessing something is not working correctly there for some reason. Not sure if it's coordinate vector related, or the isoperiodicity itself.

A few questions:
- Do we want to maintain compatibility with both forms of periodicity? 
  - Isoperiodicity seems to be our more preferred way, but I'd still be in favor of keeping both compatibilities (even if I don't fully understand the consequences between each approach)
- Why does permuting the CellCoordinateDM result in something satisfactory to libCEED?

**Comment by knepley** [comment]
The second question should be easy to answer. Make a simple test in ex8 that shows the problem. This is how we tracked down everything Rezgar was asking about. It should be as simple as a 1 or 2 cell mesh and certain degree coordinates. The reason I want to do this is that Rezgar and I looked at it, and those coordinates were in tensor ordering, so I want to see what you are seeing.

**Comment by rezgarshakeri** [comment]
Yeah, you can check the indices. For example by running
```
./ex8 -dm_plex_dim 2 -petscspace_degree 1 -dm_plex_simplex 0 -dm_plex_box_faces 3,2 -dm_plex_box_bd periodic,none -view_coord
```
we get
```
[...]

DM box offsets: num_elem 6, size 4, comp 1, dof 9
0: 0 1 3 4
0: 1 2 4 5
0: 2 0 5 3
0: 3 4 6 7
0: 4 5 7 8
0: 5 3 8 6
DM coords offsets: num_elem 6, size 4, comp 2, dof 18
0: 0 2 6 8
 0:   0.0000e+00   0.0000e+00
 0:   3.3333e-01   0.0000e+00
 0:   0.0000e+00   5.0000e-01
 0:   3.3333e-01   5.0000e-01
0: 2 4 8 10
 0:   3.3333e-01   0.0000e+00
 0:   6.6667e-01   0.0000e+00
 0:   3.3333e-01   5.0000e-01
 0:   6.6667e-01   5.0000e-01
0: 4 0 10 6
 0:   6.6667e-01   0.0000e+00
 0:   0.0000e+00   0.0000e+00
 0:   6.6667e-01   5.0000e-01
 0:   0.0000e+00   5.0000e-01
0: 6 8 12 14
 0:   0.0000e+00   5.0000e-01
 0:   3.3333e-01   5.0000e-01
 0:   0.0000e+00   1.0000e+00
 0:   3.3333e-01   1.0000e+00
0: 8 10 14 16
 0:   3.3333e-01   5.0000e-01
 0:   6.6667e-01   5.0000e-01
 0:   3.3333e-01   1.0000e+00
 0:   6.6667e-01   1.0000e+00
0: 10 6 16 12
 0:   6.6667e-01   5.0000e-01
 0:   0.0000e+00   5.0000e-01
 0:   6.6667e-01   1.0000e+00
 0:   0.0000e+00   1.0000e+00
```
which you can see the indices for both `dm` and `cdm` are in correct tensor ordering as shown below
![periodic_x](https://github.com/CEED/libCEED/assets/42816410/f8ce2cec-0d38-47aa-86ed-b5bfec0d68a5)

(note you can run with `-dm_plex_box_bd non, periodic` which makes the top and bottom indices the same)
That means we correctly permute `dm` and `cdm` by `DMPlexSetClosurePermutationTensor` function.

**Comment by jrwrigh** [comment]
So modifying the ex8 file by:
```diff
diff --git i/src/dm/impls/plex/tutorials/ex8.c w/src/dm/impls/plex/tutorials/ex8.c
index 09623a66ce3..36e3314e9c7 100644
--- i/src/dm/impls/plex/tutorials/ex8.c
+++ w/src/dm/impls/plex/tutorials/ex8.c
@@ -128,7 +128,7 @@ int main(int argc, char **argv)
     PetscCall(ISDestroy(&valueIS));
   }
   if (view_coord) {
-    DM       cdm;
+    DM       cdm, cell_dm;
     Vec      X;
     PetscInt cdim;

@@ -137,6 +137,10 @@ int main(int argc, char **argv)
     PetscCall(DMGetCoordinateDM(dm, &cdm));
     PetscCall(PetscObjectSetName((PetscObject)cdm, "coords"));
     if (tensor) PetscCall(DMPlexSetClosurePermutationTensor(cdm, PETSC_DETERMINE, NULL));
+
+    PetscCall(DMGetCellCoordinateDM(dm, &cell_dm));
+    if (tensor && cell_dm) PetscCall(DMPlexSetClosurePermutationTensor(cell_dm, PETSC_DETERMINE, NULL));
+
     for (c = cStart; c < cEnd; ++c) {
       const PetscScalar *array;
       PetscScalar       *x = NULL;
@@ -152,6 +156,10 @@ int main(int argc, char **argv)
     PetscCall(ViewOffsets(dm, NULL));
     PetscCall(DMGetCoordinatesLocal(dm, &X));
     PetscCall(ViewOffsets(cdm, X));
+    if (cell_dm) {
+      PetscCall(DMGetCellCoordinatesLocal(dm, &X));
+      PetscCall(ViewOffsets(cell_dm, X));
+    }
   }
   PetscCall(DMDestroy(&dm));
   PetscCall(PetscFinalize());
```

And forcing the permutation by (un)commenting:
```diff
diff --git i/src/dm/impls/plex/plex.c w/src/dm/impls/plex/plex.c
index 62982578c12..a20d9e002a0 100644
--- i/src/dm/impls/plex/plex.c
+++ w/src/dm/impls/plex/plex.c
@@ -5729,6 +5729,7 @@ static PetscErrorCode PetscSectionFieldGetTensorDegree_Private(DM dm, PetscSecti
     *k = (PetscInt)PetscCeilReal(PetscPowReal(dual_space_size / *Nc, 1.0 / dim)) - 1;
     PetscCall(PetscDualSpaceLagrangeGetContinuity(dsp, continuous));
     PetscCall(PetscDualSpaceLagrangeGetTensor(dsp, tensor));
+    // *continuous = PETSC_TRUE;
   }
   PetscFunctionReturn(PETSC_SUCCESS);
 }
```

and running 
```
./ex8 -dm_plex_dim 2 -petscspace_degree 1 -dm_plex_simplex 0 -dm_plex_box_faces 3,2 -dm_plex_box_bd periodic,none -view_coord -dm_sparse_localize false
```

The un-permuted CellCoordinateDM results in:
```
DM DM_0x15407b0_0 offsets: num_elem 6, size 4, comp 2, dof 48
0: 0 2 4 6
 0:   0.0000e+00   0.0000e+00
 0:   3.3333e-01   0.0000e+00
 0:   3.3333e-01   5.0000e-01
 0:   0.0000e+00   5.0000e-01
0: 8 10 12 14
 0:   3.3333e-01   0.0000e+00
 0:   6.6667e-01   0.0000e+00
 0:   6.6667e-01   5.0000e-01
 0:   3.3333e-01   5.0000e-01
0: 16 18 20 22
 0:   6.6667e-01   0.0000e+00
 0:   1.0000e+00   0.0000e+00
 0:   1.0000e+00   5.0000e-01
 0:   6.6667e-01   5.0000e-01
0: 24 26 28 30
 0:   0.0000e+00   5.0000e-01
 0:   3.3333e-01   5.0000e-01
 0:   3.3333e-01   1.0000e+00
 0:   0.0000e+00   1.0000e+00
0: 32 34 36 38
 0:   3.3333e-01   5.0000e-01
 0:   6.6667e-01   5.0000e-01
 0:   6.6667e-01   1.0000e+00
 0:   3.3333e-01   1.0000e+00
0: 40 42 44 46
 0:   6.6667e-01   5.0000e-01
 0:   1.0000e+00   5.0000e-01
 0:   1.0000e+00   1.0000e+00
 0:   6.6667e-01   1.0000e+00
```
which is not in tensor-product ordering, at least by the first element.

Doing the permutation (forcing `*continuous = PETSC_TRUE;`) results in:
```
DM DM_0x165d7b0_0 offsets: num_elem 6, size 4, comp 2, dof 48
0: 0 2 6 4
 0:   0.0000e+00   0.0000e+00
 0:   3.3333e-01   0.0000e+00
 0:   0.0000e+00   5.0000e-01
 0:   3.3333e-01   5.0000e-01
0: 8 10 14 12
 0:   3.3333e-01   0.0000e+00
 0:   6.6667e-01   0.0000e+00
 0:   3.3333e-01   5.0000e-01
 0:   6.6667e-01   5.0000e-01
0: 16 18 22 20
 0:   6.6667e-01   0.0000e+00
 0:   1.0000e+00   0.0000e+00
 0:   6.6667e-01   5.0000e-01
 0:   1.0000e+00   5.0000e-01
0: 24 26 30 28
 0:   0.0000e+00   5.0000e-01
 0:   3.3333e-01   5.0000e-01
 0:   0.0000e+00   1.0000e+00
 0:   3.3333e-01   1.0000e+00
0: 32 34 38 36
 0:   3.3333e-01   5.0000e-01
 0:   6.6667e-01   5.0000e-01
 0:   3.3333e-01   1.0000e+00
 0:   6.6667e-01   1.0000e+00
0: 40 42 46 44
 0:   6.6667e-01   5.0000e-01
 0:   1.0000e+00   5.0000e-01
 0:   6.6667e-01   1.0000e+00
 0:   1.0000e+00   1.0000e+00
```
which is in tensor-product ordering.

So the original ordering of the CellCoordinateDM's discontinuous field is not tensor-product. Where is that set?

**Comment by rezgarshakeri** [comment]
I updated `ex8` as you mentioned in main branch (so that means with the change Matt and I made) 
```diff
--- a/src/dm/impls/plex/tutorials/ex8.c
+    DM       cdm, cell_dm;
     Vec      X;
     PetscInt cdim;
 
@@ -137,6 +137,10 @@ int main(int argc, char **argv)
     PetscCall(DMGetCoordinateDM(dm, &cdm));
     PetscCall(PetscObjectSetName((PetscObject)cdm, "coords"));
     if (tensor) PetscCall(DMPlexSetClosurePermutationTensor(cdm, PETSC_DETERMINE, NULL));
+
+    PetscCall(DMGetCellCoordinateDM(dm, &cell_dm));
+    if (tensor && cell_dm) PetscCall(DMPlexSetClosurePermutationTensor(cell_dm, PETSC_DETERMINE, NULL));
+
     for (c = cStart; c < cEnd; ++c) {
       const PetscScalar *array;
       PetscScalar       *x = NULL;
@@ -151,7 +155,10 @@ int main(int argc, char **argv)
     }
     PetscCall(ViewOffsets(dm, NULL));
     PetscCall(DMGetCoordinatesLocal(dm, &X));
-    PetscCall(ViewOffsets(cdm, X));
+    PetscCall(ViewOffsets(cdm, NULL));
+    if (cell_dm) {
+       PetscCall(ViewOffsets(cell_dm, NULL));
+    }
   }
```
but not `plex.c` and run
```
./ex8 -dm_plex_dim 2 -petscspace_degree 1 -dm_plex_simplex 0 -dm_plex_box_faces 3,2 -dm_plex_box_bd periodic,none -view_coord -dm_sparse_localize false
```
which gives
```
DM box offsets: num_elem 6, size 4, comp 1, dof 9
0: 0 1 3 4
0: 1 2 4 5
0: 2 0 5 3
0: 3 4 6 7
0: 4 5 7 8
0: 5 3 8 6
DM coords offsets: num_elem 6, size 4, comp 2, dof 18
0: 0 2 6 8
0: 2 4 8 10
0: 4 0 10 6
0: 6 8 12 14
0: 8 10 14 16
0: 10 6 16 12
DM DM_0x84000000_0 offsets: num_elem 6, size 4, comp 2, dof 48
0: 0 2 4 6
0: 8 10 12 14
0: 16 18 20 22
0: 24 26 28 30
0: 32 34 36 38
0: 40 42 44 46
```
and shows the tensor ordering is correct for all `dm`, `cdm` and `cell_dm`. 

![Screenshot from 2024-02-12 12-00-45](https://github.com/CEED/libCEED/assets/42816410/efba4567-5544-41e3-b743-8cc7ab466831)

**Comment by rezgarshakeri** [comment]
BTW, I don't know if you expect the `cell_dm` be periodic which isn't (left/right edges don't have same indices) and makes sense to me since it is discontinuous. As far as I can tell the main branch in petsc gives correct ordering.

**Comment by rezgarshakeri** [comment]
Ah, so you expect some indices for `cdm` and `cell_dm` be the same?! But one of them is discontinuous, how can we make them the same?

**Comment by rezgarshakeri** [comment]
Ah, sorry I see what you are saying. The indices that I got for first element is `0 2 4 6` but you got `0 2 6 4`, so I drew based on indices that I got.

**Comment by rezgarshakeri** [comment]
Found it, the coordinate is wrong. This is first element
```
0: 0 2 4 6
 0:   0.0000e+00   0.0000e+00
 0:   3.3333e-01   0.0000e+00
 0:   3.3333e-01   5.0000e-01
 0:   0.0000e+00   5.0000e-01
```

**Comment by jrwrigh** [comment]
Yep. So do you agree that the `DMPlexSetClosurePermutationTensor` on main on the cell coordinate DM does not result in a tensor product ordering?

**Comment by knepley** [comment]
I was not paying close enough attention. The values in cell_dm are _not_ the tensor values on a face. Rather they are closure values pulled into the face. This is because a) they need to work for all shapes, and b) the intent was to make them a complete replacement for the closure in order to integrate.

Thus, these values are not face values (which are in tensor order), but closure values (which are in closure order), and James is right that the closure permutation should be applied to them.

**Comment by knepley** [comment]
Yes

**Comment by rezgarshakeri** [comment]
To me the indices `0 2 4 6` for cell_dm seems correct, is it possible that getting coordinate values in this case is wrong?

**Comment by jrwrigh** [comment]
I'm not sure what you mean as one is reliant on the other. The index ordering is only "correct" with respect to the order of the coordinate vector. And, generally speaking, the coordinate vector is in arbitrary order, so the index ordering is also arbitrary.

**Comment by jrwrigh** [comment]
@knepley Any idea/recommendation on how to "detect" whether the discontinuous field should be permuted? Is there a way to determine if the DM is the CellCoordinateDM for another DM?

**Comment by rezgarshakeri** [comment]
What I am saying is that you get a coordinate vector for continuous case which is permuted and the then assign the same coordinate vector to the discontinuous case which is not permuted and that leads the mismatch for coordinate values.

**Comment by rezgarshakeri** [comment]
Here is the test for what I am saying, turn off `DMPlexSetClosurePermutationTensor` for `cdm` and `cell_dm` in ex8. The original ordering for `continuous field` is counterclockwise and its coordinate (element 1) is
```
0: 0 2 8 6
 0:   0.0000e+00   0.0000e+00
 0:   3.3333e-01   0.0000e+00
 0:   3.3333e-01   5.0000e-01
 0:   0.0000e+00   5.0000e-01
```
and for discontinuous coordinate which has the tensor ordering is
```
0: 0 2 4 6
 0:   0.0000e+00   0.0000e+00
 0:   3.3333e-01   0.0000e+00
 0:   3.3333e-01   5.0000e-01
 0:   0.0000e+00   5.0000e-01
```
that means for example last node (top-right corner) in discontinuous field which should have coordinate (0.33, 0.5) has a wrong values.

**Comment by knepley** [comment]
@jrwrigh There is no marker for a DM holding values that are cellwise closures. I am not sure why we need that. Don't we know that we are dealing with the Cell Coordinates when we are permuting?

**Comment by rezgarshakeri** [comment]
Here is a drawing of what I reported above for original ordering (without calling permutation)
![Screenshot from 2024-02-12 14-39-32](https://github.com/CEED/libCEED/assets/42816410/d654a860-6d40-4dbf-86cf-7b6b289fb4e7)

Unless @knepley tells me that original ordering of discontinuous field is not-tensor ordering otherwise I think the `DMGetCellCoordinatesLocal` is not working correctly.

**Comment by jrwrigh** [comment]
> @jrwrigh There is no marker for a DM holding values that are cellwise closures. I am not sure why we need that. Don't we know that we are dealing with the Cell Coordinates when we are permuting?

Yeah, I guess that's true. Should we add another argument to `DMPlexSetClosurePermutationTensor` to force permutation of discontinuous fields then?

Like, we know what needs to be done (force the discontinuous field to permute it's ordering), but I'm not sure of the best way of implementing that.

**Comment by knepley** [comment]
@rezgarshakeri Do you mind operning an MR with you diff added to ex8? That way you and I can run the same exact thing, and I can definitively agree or not. Here is why I cannot say without looking:

    The cell coordinates are definitely in closure order. However, if the continuous coordinates had a closure permutation when coordinates were localized, I think they will also be permuted. So it could depend on when localization happens.

That is why we need a test, and to know when localization is happening.

**Comment by rezgarshakeri** [comment]
Sure, I'll create one in a bit.

**Comment by rezgarshakeri** [comment]
Here https://gitlab.com/petsc/petsc/-/merge_requests/7289

**Comment by jrwrigh** [comment]
@knepley Have you had a chance to look at Rezgar's MR? 

TBH, I'm not sure if his concern is separate to the issue I'm running into. Regardless, let me know if there's anything I can help with. I can try and sketch out [my idea above](https://github.com/CEED/libCEED/issues/1470#issuecomment-1939661700) in an MR if you'd like.

**Comment by rezgarshakeri** [comment]
I think all of these issues are related. The reason Matt and I made this change in `DMPlexSetClosurePermutationTensor` was that we realized for discontinuous field we don't need to permute the indices since the original numbering is already in a tensor ordering. So we look for continuous field to change the ordering only and we tested for mixed elasticity with different mixed elements like Q3Q1disc, Q2P0, Q2P1, ....

I see only two ways to fix the issue you have with discontinuous coordinate. (I see discontinuous coordinate as Q1disc element)

1. Discontinuous field indices be in a tensor ordering **is not correct**, therefore we need to change the ordering in this case for all degrees including your Q1disc for coordinate.
2. Discontinuous field indices be in a tensor ordering **is correct** therefore we need to fix https://gitlab.com/petsc/petsc/-/merge_requests/7289 first, since in that MR I don't call `DMPlexSetClosurePermutationTensor` and the coordinate I get from `DMGetCellCoordinatesLocal` is not correctly assigned to the indices. (for example `index 6` in discontinuous field should have coordinate `3.3333e-01   5.0000e-01` NOT `0.0000e+00   5.0000e-01`). If we fix that we don't need to touch `DMPlexSetClosurePermutationTensor`  function.

**Comment by knepley** [comment]
Sorry this is not done. I had to go to conference. I looked at Rexgar's submission, and I think this is an ordering problem, namely it depends on when localization happens. I just need to verify that this is correct and put in a guard, so that we all see the same thing.

**Comment by jrwrigh** [comment]
Ooh, I think I get what y'all are saying. If we localize the coordinates _after_ the continuous coordinates have been permuted to a tensor ordering, the discontinuous coordinates should also have that tensor ordering as well?

And no worries Matt. I remembered last night that Jed was also at a conference last week and that you might've been there too.

**Comment by rezgarshakeri** [comment]
Yeah, that's right.

**Comment by jrwrigh** [comment]
@knepley Any chance to re-look at this? Let me know if there's anything I can do.

**Comment by knepley** [comment]
I thought this was fine. Is there a problem with the code? Thanks, Matt

**Comment by jrwrigh** [comment]
Yep, the ordering of the cell coordinate DM is still inconsistent.

**Comment by knepley** [comment]
It is consistent in the PETSc example, which I say above, comes from the fact that coordinates are localized later. I think that should be a change in Ratel. Do you think it should be somewhere in PETSc?

**Comment by jeremylt** [comment]
This is unrelated to Ratel. It only applies to the fluid dynamics code we have.

**Comment by rezgarshakeri** [comment]
> Here https://gitlab.com/petsc/petsc/-/merge_requests/7289

@knepley Have you looked at this MR?I think PETSc is inconsistent.

**Comment by knepley** [comment]
@rezgarshakeri I looked. It is consistent.

**Comment by jrwrigh** [comment]
So the issue I'm seeing (detailed in [this above comment](https://github.com/CEED/libCEED/issues/1470#issuecomment-1939323251), that I've verified off of latest PETSc `main`) is that setting `DMPlexSetClosurePermutationTensor` onto the `cell_dm` does not result in the tensor product ordering of the nodes. This is because the coordinate space is discontinuous and the permutation to get the tensor product ordering is only done to continuous fields. If I force the permutation to occur, then the result is correct.

So we need to apply the tensor product permutation to the `cell_dm` somehow, without conflicting with the work Rezgar did in [PETSc MR 6964](https://gitlab.com/petsc/petsc/-/merge_requests/6964/). There currently is not a way to do that.

I guess my current confusion is why the choice of whether or not to permute is based on the continuity of the field. I don't see a connection between node ordering and continuity that would enforce that.

**Comment by knepley** [comment]
Sorry, @rezgarshakeri I meant to type "consistent" . It corrected. I do not see an error.

**Comment by knepley** [comment]
@jrwrigh I know you must be seeing something, but I cannot understand your explanation. Discontinuous fields should always in tensor order. That is why we do not reorder them.

**Comment by jrwrigh** [comment]
Ok, sorry I'm not being clear. Given the current patch for `ex8.c`:
```diff
diff --git i/src/dm/impls/plex/tutorials/ex8.c w/src/dm/impls/plex/tutorials/ex8.c
index 09623a66ce3..c690e0b6142 100644
--- i/src/dm/impls/plex/tutorials/ex8.c
+++ w/src/dm/impls/plex/tutorials/ex8.c
@@ -128,7 +128,7 @@ int main(int argc, char **argv)
     PetscCall(ISDestroy(&valueIS));
   }
   if (view_coord) {
-    DM       cdm;
+    DM       cdm, cell_dm;
     Vec      X;
     PetscInt cdim;

@@ -152,6 +155,11 @@ int main(int argc, char **argv)
     PetscCall(ViewOffsets(dm, NULL));
     PetscCall(DMGetCoordinatesLocal(dm, &X));
     PetscCall(ViewOffsets(cdm, X));
+    PetscCall(DMGetCellCoordinateDM(dm, &cell_dm));
+    if (cell_dm) {
+      PetscCall(DMGetCellCoordinatesLocal(dm, &X));
+      PetscCall(ViewOffsets(cell_dm, X));
+    }
   }
   PetscCall(DMDestroy(&dm));
   PetscCall(PetscFinalize());
```

And running the following command:
```
./ex8 -dm_plex_dim 2 -petscspace_degree 1 -dm_plex_simplex 0 -dm_plex_box_faces 3,2 -dm_plex_box_bd periodic,none -view_coord -dm_sparse_localize false
```

The cell dm reports for the first element:
```
DM DM_0x24bc400_0 offsets: num_elem 6, size 4, comp 2, dof 48
0: 0 2 4 6
 0:   0.0000e+00   0.0000e+00
 0:   3.3333e-01   0.0000e+00
 0:   3.3333e-01   5.0000e-01
 0:   0.0000e+00   5.0000e-01
 ```
 The corresponds to this diagram of the element:
 
<img src="https://github.com/CEED/libCEED/assets/20801821/ae9fa618-e9f0-4328-8986-d7f2f8b8af9e" width="300">

The ordering that it reports, `0, 2, 4, 6`, is not in tensor product ordering (which would be `0, 2, 6, 4`. Previous to !6964, we would call `DMPlexSetClosurePermutationTensor` on the cell DM to permute the ordering to tensor product. This no longer works.

> Discontinuous fields should always in tensor order. That is why we do not reorder them.

If that's what the intention is, then there is a bug, at least with the cell coordinate's discontinuous field.

**Comment by knepley** [comment]
Cool, I will run it (maybe not until tomorrow) and figure it out. Thanks for the good example.

**Comment by rezgarshakeri** [comment]
@jrwrigh I think the diagram you drew is not correct (you need to flip 4 and 6). It is actually tensor ordering the issue is that the coordinate is not assigned to each node correctly. That's what I tried to show in  https://gitlab.com/petsc/petsc/-/merge_requests/7289.
In that MR, I **don't call** `DMPlexSetClosurePermutationTensor` and I see the coordinate I get from `DMGetCellCoordinatesLocal`  is not correctly set to each nodes. For example `node 6` has coordinate `(0,0.5)`.  So I am not convinced that MR is consistent.

Prior to my MR, PESTc flipped the ordering for all fields even for discontinuous coordinate and that's why you got the correct coordinate for each node. But as I mentioned the issue is in `DMGetCellCoordinatesLocal` not index ordering.

**Comment by knepley** [comment]
@rezgarshakeri Yes, I agree. And as I say above, this is due to the order in which localization happens.

**Comment by rezgarshakeri** [comment]
Thanks for confirming. So now we know that coordinate is not correct, `node 6: 0.0000e+00   5.0000e-01` but it should be `(1/3,1/2)`. (What James showed it is exactly same example that I reported but I did it without calling tensor permutation)

I see two ways to fix this `1)` flip the index for discontinuous coordinate as we did before my MR (which I think it is not correct way) `2)` fix the coordinate inconsistency that I showed in  https://gitlab.com/petsc/petsc/-/merge_requests/7289

**Comment by jrwrigh** [comment]
I disagree that my figure is wrong; it reflects what DMPlex is reporting and thus what libCEED sees when it asks for offsets. Note that I didn't call `DMPlexSetClosurePermutationTensor` in the example I sent yesterday; my example and your MR are functionally identical. 

But we agree on everything else, including that DMPlex is incorrect. I don't care whether the indexing is at fault, or the coordinate vector is in the wrong order; the pairing is all that matters at the end of the day.

**Comment by rezgarshakeri** [comment]
> @jrwrigh I know you must be seeing something, but I cannot understand your explanation. Discontinuous fields should always in tensor order. That is why we do not reorder them.

As Matt said here, discontinuous field is already tensor ordering so the pairing of them with coordinate is wrong as we both agree. It is actually important, if index is correct that means the issue is somewhere else and we should fix that before changing anything in `DMPlexSetClosurePermutationTensor` (we both didn't call this function) . That's what I am trying to say.

**Comment by knepley** [comment]
Okay, the problem is when localization happens. I have added the test from @jrwrigh to illustrate this. I have put in some support for controlling this. Take a look at https://gitlab.com/petsc/petsc/-/merge_requests/7438 and see if it solves your problem.

**Comment by knepley** [comment]
More explanation: I was not being precise before. The coordinate localization is done in the _closure_ order. If that order is counter-clockwise, that is used, if it is tensor that is used. Thus, if we change closure ordering during the solve, there can be a mismatch with the localization order.

**Comment by jrwrigh** [comment]
I've confirmed that solution works. 

Instead of turning off default localization, then manually localizing after the tensor closure is set, is it possible to track the state of the coordinates at the time of localization, then redo the localization if the state has changed. Maybe just keeping track of the state of the local section at localization time would work? I'm not sure if `PetscSection` has a similar state-tracking feature that `Vec` and `Mat` do though.

**Comment by knepley** [comment]
@jrwrigh Let me see if I understand. We would redo localization if the ordering changes? Actually, I think this would be easiest to do when the closure order changes. We can check whether the localization has happened, and redo it if so.

**Comment by jrwrigh** [comment]
Yep, that was my thought. Didn't think about doing it when the closure changes though, that would be even better.

**Comment by jrwrigh** [comment]
Well, thinking through that, there might be a snag. Example from the fluids example:
```c
  PetscCall(DMPlexIsSimplex(dm, &is_simplex));
  // Set tensor permutation if needed
  if (!is_simplex) {
    PetscCall(DMPlexSetClosurePermutationTensor(dm, PETSC_DETERMINE, NULL));
    if (setup_coords) {
      DM dm_coord;

      PetscCall(DMGetCoordinateDM(dm, &dm_coord));
      PetscCall(DMPlexSetClosurePermutationTensor(dm_coord, PETSC_DETERMINE, NULL));
    }
  }
```

For the first `DMPlexSetClosurePermutationTensor` call, if we call `DMLocalizeCoordinates` from inside that, the coordinate DM still has BFS ordering. So the order of localization will still be wrong.

For the second `DMPlexSetClosurePermutationTensor` call, `DMLocalizeCoordinates` will ask for a coordinate DM from `dm_coord`, but it doesn't have one and it will error out.

So `DMPlexSetClosurePermutationTensor` would need to have knowledge of what "kind" of DM it's dealing with. Or have `DMPlexSetClosurePermutationTensor` change the ordering for both the passed DM and its coordinate DM, then it can call `DMLocalizeCoordinates` on the passed DM.

**Comment by knepley** [comment]
I think the above will be okay because the coordinate DM is not localized.

**Comment by jeremylt** [comment]
Building with PETSc main results in CI failing for the fluids example:
https://gitlab.com/libceed/libCEED/-/jobs/6574507102

**Comment by jrwrigh** [comment]
Is that with #1554 or without? #1554 is required to have the changes work.

**Comment by jeremylt** [comment]
Ah, I missed that part. It is  without
