### ISSUE TITLE
OCCA Backends in CI

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#426]
@dmed256, I'm getting CI errors on Travis for the OCCA backend that I can't reproduce locally.

https://travis-ci.org/CEED/libCEED/jobs/619769459?utm_medium=notification&utm_source=github_status

Any thoughts on what might be wrong and how to fix it?

**Comment by dmed256** [comment]
@jeremylt Oops, I might have accidentally broken backwards compatibility with a change I recently made. I'll fix it tonight!

**Comment by jeremylt** [comment]
Thanks!

**Comment by dmed256** [comment]
Fixed with #427

**Comment by jedbrown** [comment]
@dmed256 If #427 was intended to fix the build, it doesn't appear to have done so. We're [still failing](https://travis-ci.org/CEED/libCEED/builds/622140654) on master. I have the same issue locally with gcc-9.2. Does the test suite pass for you?
```
not ok 31 t201-elemrestriction /cpu/occa
ok 32 t201-elemrestriction /cpu/occa stdout
not ok 33 t201-elemrestriction /cpu/occa stderr
# +terminate called after throwing an instance of 'occa::exception'
# +what():
# +---[ Error ]--------------------------------------------------------------------
# +File     : /home/travis/build/CEED/libCEED/occa/src/c/types.cpp
# +Line     : 376
# +Function : kernelArg
# +Message  : A non-occaType argument was passed
# +Stack
# +9 occa::error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
# +8 occa::c::kernelArg(occaType)
# +7 /home/travis/build/CEED/libCEED/occa/lib/libocca.so(occaKernelVaRun+0x603)
# +6 /home/travis/build/CEED/libCEED/occa/lib/libocca.so(occaKernelRunN+0xb5)
# +5 /home/travis/build/CEED/libCEED/lib/libceed_test.so(+0x44ead)
# +4 /home/travis/build/CEED/libCEED/lib/libceed_test.so(CeedElemRestrictionApply+0x120)
# +3 build/t201-elemrestriction()
# +2 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)
# +1 build/t201-elemrestriction()
# +================================================================================
```

**Comment by dmed256** [comment]
@jedbrown This seems like a different error. Debugging atm

**Comment by dmed256** [comment]
Fix PR: https://github.com/libocca/occa/pull/271

There was a long-living bug in the way we launch kernels in the C API. Not sure why it only showed up now.

**Comment by jedbrown** [comment]
Thanks, it's working now locally so I'll close this issue.
